name: rusty_dlna
description: "A Flutter plugin for DLNA/UPnP device discovery and media casting, powered by Rust. Supports scanning, casting, playback control, and volume management."
version: 0.0.1
homepage: https://github.com/mdddj/rusty_dlna
repository: https://github.com/mdddj/rusty_dlna
issue_tracker: https://github.com/mdddj/rusty_dlna/issues

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  flutter_rust_bridge: ^2.11.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  ffi: ^2.1.0
  ffigen: ^9.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true
